maintainer  'Carlos Mafla'
name 'symfony-chef-vagrant'
license 'all_rights'
description 'Installs/Configures Symfony on a Vagrant box'
long_description 'Installs/Configures Symfony on a Vagrant box'
version '0.1.0'

depends 'apache2'
depends 'apt'
depends 'chef-client'
depends 'git'
depends 'php'
depends 'mysql'
depends 'sudo'
depends 'timezone-ii'
depends 'composer'
depends 'omnibus_updater'
